# Generated by Django 3.0.2 on 2020-01-22 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_name', models.CharField(help_text='Driver name is unique', max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(help_text='User name is unique', max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RideDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ride_created', models.DateTimeField(auto_now_add=True)),
                ('ride_status', models.CharField(choices=[('rq', 'Requested'), ('ac', 'Accepted'), ('dn', 'Done')], default='Requested', help_text='this field is choice field where default is Requested', max_length=2)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cabAllocation.Driver')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cabAllocation.User')),
            ],
        ),
    ]
