# Generated by Django 3.0.2 on 2020-01-18 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RideDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ride_field', models.CharField(choices=[('rq', 'Requested'), ('ac', 'Accepted'), ('dn', 'Done')], default='Requested', help_text='hk', max_length=2)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cabAllocation.Driver')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cabAllocation.User')),
            ],
        ),
    ]
