# Generated by Django 3.0.2 on 2020-01-21 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cabAllocation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ridedetails',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cabAllocation.Driver'),
        ),
    ]
