# Generated by Django 3.0.2 on 2020-01-20 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabAllocation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ridedetails',
            name='ride_field',
        ),
        migrations.AddField(
            model_name='ridedetails',
            name='ride_status',
            field=models.CharField(choices=[('rq', 'Requested'), ('ac', 'Accepted'), ('dn', 'Done')], default='Requested', help_text='this field is choice field where default is Requested', max_length=2),
        ),
        migrations.AlterField(
            model_name='driver',
            name='driver_name',
            field=models.CharField(help_text='Driver name is unique', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_name',
            field=models.CharField(help_text='User name is unique', max_length=200, unique=True),
        ),
    ]
